apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: gram-thread

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: viprana21/gram-thread-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: PORT
              value: "8000"

            - name: DB_HOST
              value: "mysql"

            - name: DB_PORT
              value: "3306"

            - name: DB_USERNAME
              value: "root"

            - name: DB_PASSWORD
              value: "root123"

            - name: DB_NAME
              value: "gramthread"

            - name: JWT_SECRET
              value: "mysecretkey123"
