import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AnouncementNavbar from "@/components/Header/AnouncementNavBar";
import NavBar from "@/components/Header/NavBar";
import { Outfit } from "next/font/google";
import { Playfair_Display } from "next/font/google";


const outfit = Outfit({
  subsets: ["latin"],
  variable: "--sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gramthread",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

